### PR TITLE
Adding in Promise::from_future function

### PR DESCRIPTION
**Pull request by Pauan**
I did some light testing to make sure that this works correctly, but no unit tests.

### CODE REVIEW

**Comment by Pauan** [comment]
@koute Ping.

**Comment by koute** [comment]
@Pauan Yes, sorry. I'll take a more thorough look at this very soon!

**Comment by Pauan** [comment]
@koute No rush, just making sure you don't forget it.

**Comment by koute** [comment]
Hmmm.... it looks mostly good to me! I'll merge it, although I'd *really* like some tests before stabilizing this. (That, and I guess wait for `futures 0.2`? I see that there is already `0.2.0-alpha` so it might be worthwhile to slowly start working on it.)

Anyway, thanks!

**Comment by Pauan** [comment]
I agree that unit tests would be great, but that will require #128 to be fixed first.

**Pull request merged**
