### PR TITLE
Add the 'fullscreenchange' event

### PR DESCRIPTION
**Pull request by ryanisaacg**

### CODE REVIEW

**Comment by koute** [comment]
Thanks for the PR!

1. Are you absolutely sure that the event is of type `FullscreenChangeEvent`? The linked specs don't seem to say anything about its type, and the MDN specifies `Event` as its interface. Have you checked whenever this actually works?
2. You forgot to export it in `src/lib.rs`. (:

**Comment by ryanisaacg** [comment]
Whoops, thanks for catching those! I've pushed fixes.

**Comment by ryanisaacg** [comment]
@koute Bumping this if you have time to take a look?

**Comment by koute** [comment]
Sorry for the delay. Thanks!

**Comment by ryanisaacg** [comment]
@koute If this could make it into a release as soon as it's convenient, I would appreciate it.

**Comment by koute** [comment]
@ryanisaacg Sure thing! Done!

**Pull request merged**
