### PR TITLE
Expose data() on ImageData

### PR DESCRIPTION
**Pull request by tversteeg**

### CODE REVIEW

**Comment by Pauan** [comment]
`set_data` shouldn't exist, since `data` is read-only.

It also might be a good idea to rename `get_data` to just `data`.

**Comment by tversteeg** [comment]
How can the data be changed if it's read-only?

**Comment by Pauan** [comment]
The `Uint8ClampedArray` which is returned by `data` is mutable, but the `data` property itself is read-only.

**Comment by tversteeg** [comment]
I've rebased my comment and just exposed `data`, is this what you had in mind?

**Comment by Pauan** [comment]
It looks good to me, just need to wait for @koute to review it.

Just a note that this isn't quite enough to support what you want, because `TypedArray` doesn't currently have any methods to mutate it, so those would have to be added as well.

**Comment by mathieucaroff** [comment]
I've had a look at the [documentation of TypedArray](https://docs.rs/stdweb/0.4.20/stdweb/web/struct.TypedArray.html), and it's not clear to me how a TypedArray allows being written to.

**Comment by Pauan** [comment]
@mathieucaroff See my comment right above yours.

**Pull request closed without merging**
