### PR TITLE
Futures 0.3

### PR DESCRIPTION
**Pull request by Pauan**
It was actually a lot easier than I thought to convert from Futures 0.2 to 0.3 (it required very little code changes).

Breaking changes:

* Now uses Futures 0.3 rather than 0.2 [(which has various breaking changes of its own)](https://github.com/rust-lang-nursery/futures-rs/blob/master/CHANGELOG.md).
* `PromiseFuture::spawn_local` has been changed to `spawn_local`
* `PromiseFuture::print_error_panic` has been changed to `print_error_panic`
* The `experimental_features_which_may_break_on_minor_version_bumps` and `futures-support` features now require Nightly Rust.

New additions:

* It's now possible to use `async` + `await!` + `join!` + `try_join!` syntax :tada: (I added a `promise` example which demonstrates this).
* New `unwrap_future` function (which internally uses `print_error_panic`)

The breaking changes and new additions only affect people who are using the `experimental_features_which_may_break_on_minor_version_bumps` feature, so this does not require a major version bump.

### CODE REVIEW

**Comment by Pauan** [comment]
It's easiest to review the changes [with whitespace disabled](https://github.com/koute/stdweb/pull/282/files?w=1).

**Comment by Pauan** [comment]
**Note:** Futures 0.3 provides a compatibility shim so that it's possible to use 0.1 Futures with 0.3. However it doesn't provide a shim from 0.2 to 0.3. Perhaps that could be added in?

**Comment by Pauan** [comment]
Okay, I tried various things, and I wasn't able to get the example working with Stable or Beta Rust.

And even without the `futures` example, Stable and Beta still break (why? they shouldn't be building with the `experimental_features_which_may_break_on_minor_version_bumps` feature)

I'm pretty stumped here, doesn't the Travis scripts have support for running some examples only on nightly? I tried that, but it *still* doesn't seem to be working.

**Comment by koute** [comment]
> And even without the `futures` example, Stable and Beta still break (why? they shouldn't be building with the `experimental_features_which_may_break_on_minor_version_bumps` feature)

You mean even if you **completely** delete that example? Is `cargo` still generating an error for a dependency which is gated with a disabled feature flag?

**Comment by Pauan** [comment]
@koute Yes:

https://travis-ci.org/koute/stdweb/builds/430253300?utm_source=github_status&utm_medium=notification

Even with the `futures` example completely deleted, and everything feature-gated behind `futures-support` *and* `nightly`.

**Comment by Pauan** [comment]
Oh, I think I figured it out: the `drag` example uses `experimental_features_which_may_break_on_minor_version_bumps`.

And Travis always uses the `ci/run_tests.sh` file which is defined in `master`, so I can't fix it to exclude `examples/drag` and `examples/futures` from Stable/Beta Rust.

**Comment by Pauan** [comment]
(The tests pass, but it's not ready to merge yet, I still need you to exclude the `examples/drag` and `examples/future` from the Stable/Beta Rust on Travis).

**Comment by Pauan** [comment]
Actually, the `drag` example doesn't seem to be using futures at all, I wonder why it uses the `experimental_features_which_may_break_on_minor_version_bumps` feature...?

**Comment by Pauan** [comment]
I got everything working, *except* I had to remove `futures` from the `Cargo.toml`, which means that anybody trying to run the example will get this error:

```
error: error: current package believes it's in a workspace when it's not:
current:   C:\Users\Pauan\Shared Folders\NixOS\stdweb\examples\futures\Cargo.toml
workspace: C:\Users\Pauan\Shared Folders\NixOS\stdweb\examples\Cargo.toml

this may be fixable by adding `futures` to the `workspace.members` array of the manifest located at: C:\Users\Pauan\Shared Folders\NixOS\stdweb\examples\Cargo.toml
```

I had tried adding `futures` to `NIGHTLY_EXAMPLES`, but it didn't seem to help. I'm not sure how the Travis scripts work, so I can't fix that.

This is ready to merge, except for the above mentioned error.

**Comment by Pauan** [comment]
@koute Ping.

**Comment by koute** [comment]
Apologies for the delay!

Looks mostly good to me! Thanks! I'll try to do something about the example.

**Comment by koute** [comment]
Hmm... it looks like the futures crates are broken on the current nightly (4141a4079 2018-09-25):

```
error[E0432]: unresolved import `core::pin::PinMut`
 --> /home/kou/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.6/src/future.rs:4:5
  |
4 | use core::pin::PinMut;
  |     ^^^^^^^^^^^^^^^^^ no `PinMut` in `pin`
error[E0432]: unresolved imports `core::future::FutureObj`, `core::future::LocalFutureObj`, `core::future::UnsafeFutureObj`
 --> /home/kou/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.6/src/future.rs:6:32
  |
6 | pub use core::future::{Future, FutureObj, LocalFutureObj, UnsafeFutureObj};
  |                                ^^^^^^^^^  ^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^ no `UnsafeFutureObj` in `future`
  |                                |          |
  |                                |          no `LocalFutureObj` in `future`
  |                                no `FutureObj` in `future`. Did you mean to use `Future`?

error[E0432]: unresolved import `core::pin::PinMut`
 --> /home/kou/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.6/src/stream/mod.rs:5:5
  |
5 | use core::pin::PinMut;
  |     ^^^^^^^^^^^^^^^^^ no `PinMut` in `pin`
```

...so I guess we first need to wait for them to be updated?

On the bright side the editions are now stabilized it seems.

**Comment by Pauan** [comment]
@koute Yeah, there's some (extremely recent) breaking changes that need to land first: https://github.com/rust-lang-nursery/futures-rs/issues/1265

If editions are stabilized, then we can probably re-enable the `futures` example?

**Comment by koute** [comment]
> If editions are stabilized, then we can probably re-enable the `futures` example?

Yep. Although only after they're actually on stable. (They're only stable on nightly.) Until then I'll just copy that example over to a separate directory and make it nightly-only.

**Pull request merged**
